version: '3'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://10.10.129.24:3306/xxl_job?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=970412@wcx.com --spring.datasource.hikari.connection-timeout=30000"
    ports:
      - 9999:8080
    volumes:
      - ./logs/:/data/applogs/xxl-job/


docker run -e PARAMS=" --server.port=7397 --spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8 --spring.datasource.username=root --spring.datasource.password=970412@wcx.com" -p 9999:8080 -v /logs/xxl-job:/data/applogs --name xxl-job-admin --restart=always  -d xuxueli/xxl-job-admin:2.3.0