version: '3'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: xxl-job-admin
    networks:
      - net-xxl
    environment:
      PARAMS: "--spring.datasource.url=jdbc:mysql://127.0.0.1:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai  --spring.datasource.username=root  --spring.datasource.password=970412@wcx.com"
    ports:
      - 9999:8080
    volumes:
      - ./logs/:/data/applogs/xxl-job/
networks:
  net-xxl:
    external: false

